[project]
name = "mcp-server"
version = "0.1.0"
description = "Educhain Server for Assessment"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "educhain>=0.3.10",
    "mcp[cli]>=1.10.1",
]
